var da_rimeligDankFest = {
  "gamePackID": "da_rimeligDankFest",
  "gamePackName": "Rimelig Dank Fest",
  "questions": [
// Questions

"Jeg har aldrig slugt (storytime hvis der kun er 1 der drikker)",
"Jeg har aldrig røget dank",
"Jeg har aldrig fistet en, med hele min hånd (storytime hvis der kun er 1 der drikker)",
"Jeg har aldrig fistet",
"Jeg har aldrig modtaget anal",
"Jeg har aldrig givet anal",
"FÆLLES SKÅL!",
"Jeg har aldrig haft et bad trip på stoffer (storytime hvis der kun er 1 der drikker)",
"Jeg har aldrig taget kokain",
"Jeg har aldrig taget svampe",
"Jeg har aldrig taget DMT",
"Jeg har aldrig spist en hashkage",
"Jorden er flad...",
"DIN MOR!",
"Fæaooolleess SKÅEEALLL!!",
"NASA har opdigtet alt",
"Jeg har aldrig tændt på tis",
"Jeg har aldrig hallucineret på stoffer (storytime hvis der kun er 1 der drikker)",
"Jeg har aldrig spinnet en fidget spinner",
"Jeg har aldrig ville have sex med nogen i dette rum",
"Jeg har aldrig knækket mig, for derefter at gå ud og kysse med en person (storytime hvis der kun er 1 der drikker)",
"Jeg har aldrig været afhængig af porno",
"Jeg har aldrig været fuld og høj på samme tid",
"Jeg har aldrig røget weed op til en skoledag (storytime hvis der kun er 1 der drikker)",
"Jeg har aldrig røget 420 i skolen (storytime hvis der kun er 1 der drikker)",
"Jeg har aldrig smagt mit eget sæd/pussyjuice (storytime hvis der kun er 1 der drikker)",
"Jeg har aldrig fået et blackout af alkohol",
"Jeg har aldrig surfet porno på skolen",
"Jeg har aldrig onaneret til hentai",
"Jeg har aldrig snuset",
"Jeg har aldrig surfet porno",
"Jeg har aldrig prøvet at ville have sex med en af samme køn",
"Jeg har aldrig haft sex med en af samme køn (storytime hvis der kun er 1 der drikker)",
"Jeg har aldrig gået kold før tolv",
"Jeg har aldrig set et familiemedlem være fuld",
"Jeg har aldrig onaneret",
"FÆLLES SKÅÅÅÅÅÅAAALLL!!!",
"Jeg har aldrig haft sex",
"Jeg har aldrig skidt i en håndvask (storytime hvis der kun er 1 der drikker)",
"Jeg har aldrig pisset i en håndvask",
"Jeg har aldrig været i tvivl om jeg har gjort nogen gravid (storytime hvis der kun er 1 der drikker)",
"Jeg har aldrig købt porno (blad, abonnement til side etc.) (storytime hvis der kun er 1 der drikker)",
"Jeg har aldrig sendt nøgenbilleder",
"Jeg har aldrig modtaget nøgenbilleder",
"Jeg har aldrig fået et blowjob mens jeg har kørt bil",
"Jeg har aldrig været utro",
"Jeg har aldrig været i et nøgenløb",
"Jeg har aldrig haft sex i en sovepose",
"Jeg har aldrig brugt et sexlegetøj til at onanere med",
"Jeg har aldrig haft sex i en pool, havet etc. (storytime hvis der kun er 1 der drikker)",
"Jeg har aldrig drukket dato (5 liter øl på under 24 timer)",
"Jeg har aldrig spanket en under sex",
"Jeg er aldrig blevet spanket under sex",
"Jeg er aldrig begyndt at bløde under sex",
"Jeg har aldrig scoret min lærer/gamle lærer (storytime hvis der kun er 1 der drikker)",
"Jeg har aldrig tændt på at blive kvalt",
"Jeg har aldrig tændt på at kvæle nogen",
"Jeg har aldrig tændt på bondage",
"Jeg har aldrig haft en trekant (storytime hvis der kun er 1 der drikker)",
"Jeg har aldrig tændt på at have min egen finger i røven",
"Jeg har aldrig fået en bøde",
"Jeg har aldrig været i spjældet (storytime hvis der kun er 1 der drikker)",
"Jeg har aldrig fået/givet et blowjob",
"Jeg har aldrig blevet slikket/slikket nogen)",
"Jeg har aldrig drukket mig stiv på skolen (storytime hvis der kun er 1 der drikker)",
"Jeg har aldrig stukket to fingre i halsen på mig selv",
"Jeg har aldrig snavet med en af samme køn",
"Jeg har aldrig kastet op på grund af alkohol",
"Jeg har aldrig prøvet amfetamin",
"Jeg har aldrig lavet italieneren (fisting)",
"Jeg har aldrig prøvet snuff",
"Jeg har aldrig set noget jeg fortrød (storytime for alle!)",
"Jeg har aldrig set Rick and Morty",
"Jeg har aldrig set lesbian porn",
"Jeg har aldrig set nogen foran mig i aktion",
"Jeg har aldrig SKÅL!",
"Jeg har aldrig fået slag af et familiemedlem",
"Jeg har aldrig uddelt slag til et familiemedlem",
"Jeg har aldrig kysset med en, hvor jeg fortrød det bagefter",
"Jeg har aldrig intimbarberet",
"Jeg har aldrig barberet mit røvhul (storytime hvis der kun er 1 der drikker)",
"Jeg har aldrig kommet til at skære mig selv under intimbarbering  (storytime hvis der kun er 1 der drikker)",
"Jeg har aldrig gået i minus på kortet",
"Jeg har aldrig skåret noget af et dyr (storytime hvis der kun er 1 der drikker)",
"Jeg har aldrig kørt i bil (ulovligt) påvirket af alkohol (storytime hvis der kun er 1 der drikker)",
"Jeg har aldrig dabbet",
"Jeg har aldrig været afhænig af alkohol",
"Jeg har aldrig været afhænig af computerspil",
"Jeg har aldrig været afhængig af snus",
"Jeg har aldrig været afhængig af smøger",
"Jeg har aldrig glemt navnet på den jeg vågnede op med dagen efter (storytime hvis der kun er 1 der drikker)",
"Jeg har aldrig fået et blowjob mens jeg så TV (storytime hvis der kun er 1 der drikker)",
"Jeg har aldrig knækket mig af snus",
"Fælles skål",
"Jeg har aldrig onaneret på skolen (storytime hvis der kun er 1 der drikker)",
"Drenge: Jeg har aldrig suttet en pik (storytime hvis der kun er 1 der drikker)",
"Jeg har aldrig tørret mig for at der så går hul på papiret eller at jeg rammer ved siden af... (storytime hvis der kun er 1 der drikker)",
"Jeg har aldrig haft en kønssygdom (storytime hvis der kun er 1 der drikker)",
"Jeg har aldrig haft sex op af et køkkenbord (storytime hvis der kun er 1 der drikker)",
"Jeg er aldrig blevet anholdt (storytime hvis der kun er 1 der drikker)",
"Jeg har aldrig fået lavet en intimpiercing (storytime hvis der kun er 1 der drikker)",
"Jeg har aldrig bustet mine forældre (storytime hvis der kun er 1 der drikker)"

]};
