var hyggeligFest = [
  "Jeg har aldrig slugt",
  "Jeg har aldrig røget dank",
  "Jeg har aldrig fistet en, med hele min hånd",
  "Jeg har aldrig fistet",
  "Jeg har aldrig modtaget anal",
  "Jeg har aldrig givet anal",
  "FÆLLES SKÅL!",
  "Jeg har aldrig haft et bad trip",
  "Jeg har aldrig taget kokain",
  "Jeg har aldrig taget svampe",
  "Jeg har aldrig spist en edible (hashkage)",
  "Jeg har aldrig selv haft en hashplante",
  "Jorden er flad...",
  "DIN MOR!",
  "Fæaooolleess SKÅEEALLL!!",
  "NASA har opdigtet alt",
  "Jeg har aldrig tændt bare lidt på tis",
  "Jeg har aldrig hallucineret på stoffer",
  "Jeg har aldrig spinnet en fidget spinner",
  "Jeg har aldrig ville have sex med nogen i dette rum",
  "Jeg har aldrig lige knækket mig, for derefter at gå ud og kysse/snave en",
  "Jeg har aldrig været afhængig af porno",
  "Jeg har aldrig været fuld og høj på samme tid",
  "Jeg har aldrig røget weed op til en skoledag",
  "Jeg har aldrig røget 420 i skolen",
  "Jeg har aldrig smagt mit eget sæd eller slikket min hånd for pussyjuice",
  "Jeg har aldrig fået et blackout af alkohol, weed...",
  "Jeg har aldrig surfet porno på skolen",
  "Jeg har aldrig handlet ulovligt på det mørke net",
  "Jeg har aldrig onaneret til hentai",
  "Jeg har aldrig snuset",
  "Jeg har aldrig fået under 4 til noget der gjaldt",
  "Jeg har aldrig af egen fri vilje surfet porno",
  "Jeg har aldrig prøvet at ville have sex med en af samme køn",
  "Jeg har aldrig gået kold før tolv",
  "Jeg har aldrig set et familiemedlem være fuld",
  "Jeg har aldrig onaneret",
  "FÆLLES SKÅÅÅÅÅÅAAALLL!!!",
  "Jeg har aldrig haft sex",
  "Jeg har aldrig fået 12 til noget der gjaldt",
  "Jeg har aldrig betalt for sex (behøver ikke kun at være penge)",
  "Jeg har aldrig skidt i en håndvask",
  "Jeg har aldrig pisset i en håndvask",
  "Jeg har aldrig været i tvivl om jeg har gjort nogen gravid",
  "Jeg har aldrig købt porno (blad, abonnement til side etc.)",
  "Jeg har aldrig sendt nøgenbilleder",
  "Jeg har aldrig modtaget nøgenbilleder",
  "Jeg har aldrig fået blowjob mens jeg kører bil eller givet blowjob til chaufføren",
  "Jeg har aldrig blevet filmet ornanere",
  "Jeg har aldrig blevet filmet have sex",
  "Jeg har aldrig været utro",
  "Jeg har aldrig været i et nøgenløb",
  "Jeg har aldrig haft sex med en, mens der har været andre i rummet der ikke må vide det",
  "Jeg har aldrig haft sex i en sovepose",
  "Jeg har aldrig brugt noget til at onanere med",
  "Jeg har aldrig haft sex i en pool, havet etc.",
  "Jeg har aldrig jeg har aldrig drukket dato",
  "Jeg har aldrig lugtet til min hånd for bagefter at dufte til den",
  "Jeg har adlrig spanket en under sex",
  "Jeg har aldrig blevet spanket under sex",
  "Jeg har aldrig begyndt at bløde under sex",
  "Jeg har aldrig scoret min lærer/gamle lærer",
  "Jeg har aldrig tændt på at blive kvalt",
  "Jeg har aldrig tændt på at kvæle nogen",
  "Jeg har aldrig tændt på at binde nogen under sex",
  "Jeg har aldrig tændt på at blive bundet under sex",
  "Jeg har aldrig haft en trekant",
  "Jeg har aldrig tændt på at have min egen finger i røven",
  "Jeg har aldrig fået en bøde",
  "Jeg har aldrig været i spjældet",
  "Jeg har aldrig fået/givet et blowjob",
  "Jeg har aldrig blevet slikket/slikket nogen)",
  "Jeg har aldrig drukket mig stiv på skolen",
  "Jeg har aldrig været fuld mindst en gang om dagen, i fem eller flere dage i streg",
  "Jeg har aldrig været på Roskilde",
  "Jeg har adrig stukket to fingre i halsen på mig selv"
];
